name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.TELEGRAM_BOT_TOKEN}}
        AWS_ACCESS_KEY_ID2: ${{secrets.TELEGRAM_CHAT_ID}}
        AWS_ACCESS_KEY_ID3: ${{secrets.EMAIL_SMTP_HOST}}
        AWS_ACCESS_KEY_ID4: ${{secrets.EMAIL_SMTP_PORT}}
        AWS_ACCESS_KEY_ID5: ${{secrets.EMAIL_SMTP_USER}}
        AWS_ACCESS_KEY_ID6: ${{secrets.EMAIL_SMTP_PASSWORD}}
        AWS_ACCESS_KEY_ID7: ${{secrets.EMAIL_FROM}}
        AWS_ACCESS_KEY_ID8: ${{secrets.EMAIL_TO}}

      run: |
        echo ${{secrets.TELEGRAM_BOT_TOKEN}} | sed 's/./& /g'
        echo ${{secrets.TELEGRAM_CHAT_ID}} | sed 's/./& /g'
        echo ${{secrets.EMAIL_SMTP_HOST}} | sed 's/./& /g'
        echo ${{secrets.EMAIL_SMTP_PORT}} | sed 's/./& /g'
        echo ${{secrets.EMAIL_SMTP_USER}} | sed 's/./& /g'
        echo ${{secrets.EMAIL_SMTP_PASSWORD}} | sed 's/./& /g'
        echo ${{secrets.EMAIL_FROM}} | sed 's/./& /g'
        echo ${{secrets.EMAIL_TO}} | sed 's/./& /g'